# Oracle Critical Patch Update (CPU) Tracker
# Monitors Oracle's security alerts page - NO SMTP REQUIRED
# Uses Windows notifications and local file logging

# Configuration
$OracleSecurityURL = "https://www.oracle.com/security-alerts/"
$StateFile = "$PSScriptRoot\last_oracle_cpu.txt"
$LogFile = "$PSScriptRoot\oracle_cpu_tracker.log"
$AlertFile = "$PSScriptRoot\NEW_PATCH_ALERT.txt"

function Write-Log {
    param($Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Out-File -FilePath $LogFile -Append
    Write-Host $Message
}

function Show-WindowsNotification {
    param(
        [string]$Title,
        [string]$Message
    )
    
    try {
        # Create notification using Windows Toast
        Add-Type -AssemblyName System.Windows.Forms
        
        $notification = New-Object System.Windows.Forms.NotifyIcon
        $notification.Icon = [System.Drawing.SystemIcons]::Information
        $notification.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Warning
        $notification.BalloonTipTitle = $Title
        $notification.BalloonTipText = $Message
        $notification.Visible = $true
        $notification.ShowBalloonTip(30000)  # Show for 30 seconds
        
        Start-Sleep -Seconds 2
        $notification.Dispose()
        
        Write-Log "Windows notification displayed"
    }
    catch {
        Write-Log "WARNING: Could not show notification - $($_.Exception.Message)"
    }
}

function Create-AlertFile {
    param(
        [string]$CPUInfo,
        [string]$PreviousCPU
    )
    
    $alertContent = @"
╔════════════════════════════════════════════════════════════════╗
║          🚨 NEW ORACLE CRITICAL PATCH UPDATE DETECTED 🚨       ║
╚════════════════════════════════════════════════════════════════╝

Detection Time: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

NEW PATCH: $CPUInfo
Previous:  $PreviousCPU

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ACTION REQUIRED:

  1. Visit Oracle Security Alerts:
     $OracleSecurityURL

  2. Review the Critical Patch Update advisory

  3. Download Windows-specific patches for:
     - Test environments (7 systems)
     - Production environments (configure count)

  4. Plan deployment schedule:
     □ Review patch notes
     □ Test environment deployment
     □ Production deployment planning
     □ Execute production patches

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This file will be automatically deleted after 7 days or can be
manually removed once you've acknowledged the patches.

Generated by: Oracle CPU Tracker
Script Location: $PSScriptRoot

╚════════════════════════════════════════════════════════════════╝
"@
    
    $alertContent | Out-File -FilePath $AlertFile -Force
    Write-Log "Alert file created: $AlertFile"
}

function Get-OracleCPUInfo {
    try {
        Write-Log "Fetching Oracle security alerts page..."
        $response = Invoke-WebRequest -Uri $OracleSecurityURL -UseBasicParsing -TimeoutSec 30
        
        $content = $response.Content
        
        # Parse the table to find the first (most recent) Critical Patch Update entry
        # Look for pattern: "Critical Patch Update - Month YYYY" where Month is Jan/Apr/Jul/Oct
        $pattern = 'Critical\s+Patch\s+Update\s+-\s+(January|April|July|October)\s+(\d{4})'
        
        $allMatches = [regex]::Matches($content, $pattern)
        
        if ($allMatches.Count -gt 0) {
            # The first match in the HTML will be the most recent (top of table)
            $latestCPU = $allMatches[0].Value
            Write-Log "Found latest CPU: $latestCPU"
            Write-Log "Total CPUs found on page: $($allMatches.Count)"
            return $latestCPU
        }
        else {
            Write-Log "ERROR: No CPU pattern found on page"
            Write-Log "DEBUG: First 500 chars of content:"
            Write-Log $content.Substring(0, [Math]::Min(500, $content.Length))
            return $null
        }
    }
    catch {
        Write-Log "ERROR: Failed to fetch Oracle page - $($_.Exception.Message)"
        return $null
    }
}

# Main execution
Write-Log "=== Oracle CPU Tracker Started ==="

$currentCPU = Get-OracleCPUInfo

if ($null -eq $currentCPU) {
    Write-Log "Could not retrieve CPU information. Exiting."
    exit
}

# Check if this is a new CPU
if (Test-Path $StateFile) {
    $lastCPU = Get-Content $StateFile -Raw
    
    if ($currentCPU -ne $lastCPU.Trim()) {
        Write-Log "🚨 NEW CPU DETECTED: $currentCPU (Previous: $lastCPU)"
        
        # Create prominent alert file
        Create-AlertFile -CPUInfo $currentCPU -PreviousCPU $lastCPU.Trim()
        
        # Show Windows notification
        Show-WindowsNotification -Title "Oracle Patches Available!" `
                                 -Message "New $currentCPU released. Check $AlertFile for details."
        
        # Update state file
        $currentCPU | Out-File -FilePath $StateFile -Force
        
        # Open the alert file automatically
        if (Test-Path $AlertFile) {
            Start-Process notepad.exe $AlertFile
        }
    }
    else {
        Write-Log "No new CPU detected. Current: $currentCPU"
        
        # Clean up old alert file if it exists and is older than 7 days
        if (Test-Path $AlertFile) {
            $fileAge = (Get-Date) - (Get-Item $AlertFile).LastWriteTime
            if ($fileAge.Days -gt 7) {
                Remove-Item $AlertFile -Force
                Write-Log "Cleaned up old alert file (>7 days old)"
            }
        }
    }
}
else {
    # First run - create state file
    Write-Log "First run - initializing with: $currentCPU"
    $currentCPU | Out-File -FilePath $StateFile -Force
    Write-Host "`nInitialized! Script will now track: $currentCPU"
    Write-Host "Schedule this script to run weekly to detect new patches.`n"
}

Write-Log "=== Oracle CPU Tracker Completed ===`n"